name: Fetch Sdk
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email 'gamejoye@gmail.com'
          git config --global user.name 'gamejoye'
      - name: Fetch Sdk from Server
        run: |
          ls . -a
          chmod +x ./fetch-sdk.sh
          ./fetch-sdk.sh


