name: Git
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mkdir sdk
        run: rm -rf ./sdk && mkdir sdk && touch sdk/index.js
      - name: Set up Git
        run: |
          git config --global user.email 'gamejoye@gmail.com'
          git config --global user.name 'gamejoye'
      - name: Add and Commit Sdk
        run: |
          git add ./sdk
          git commit -m "chore(sdk): sdk";
      - name: Git Status
        run: git status
      - name: Push Sdk
        run: git push


