name: Git
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.email 'gamejoye@gmail.com'
          git config --global user.name 'gamejoye'
      - name: Add and Commit Sdk
        id: commit_sdk
        run: |
          git add ./sdk
          git commit -m "chore(sdk): sdk"
      - name: Run after Changes
        if: steps.commit_sdk.outcome == 'success'
        run: |
          echo "gamejoye gamejoye is run run run"
      - name: Git Status
        run: git status
      - name: Push Sdk
        run: git push


