name: Git
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mkdir sdk
        run: rm -rf ./sdk && mkdir sdk && touch sdk/index.js
      - name: Set up Git
        run: |
          export GITHUB_USER=gamejoye
          echo "GITHUB_USER=$GITHUB_USER" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}" >> $GITHUB_ENV
          git config --global user.email "gamejoye@gmail.com"
          git config --global user.name $GITHUB_USER
      - name: Add and Commit Sdk
        run: |
          git add ./sdk
          git commit -m "chore(sdk): sdk";
      - name: Git Status
        run: git status
      - name: Push Sdk
        run: git push -u origin master
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


