name: Jam Compiler Ci
on:
  push: 
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    runs-on: macos-latest-large
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - name: Set Up Environment
        run: |
          brew update
          brew install cmake
          brew install flex
          brew install bison
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."