name: deploy
run-name: Deploy To Aliyun ECS
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v4
      - name: Node Environment Setup
        uses: actions/setup-node@v4.0.1
        with:
          node-version: "20"
          cache: "npm"
      - name: Deploy To Server
        run: echo "private ssh key [ ${{ secrets.SSH_PRIVATE_KEY }} ] ."
